/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    award: Award;
    publication: Publication;
    publicationCategory: PublicationCategory;
    employee: Employee;
    officeLocation: OfficeLocation;
    mine: Mine;
    mineFeatures: MineFeature;
    project: Project;
    projectPhase: ProjectPhase;
    projectPartial: ProjectPartial;
    projectService: ProjectService;
    projectFlag: ProjectFlag;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    award: AwardSelect<false> | AwardSelect<true>;
    publication: PublicationSelect<false> | PublicationSelect<true>;
    publicationCategory: PublicationCategorySelect<false> | PublicationCategorySelect<true>;
    employee: EmployeeSelect<false> | EmployeeSelect<true>;
    officeLocation: OfficeLocationSelect<false> | OfficeLocationSelect<true>;
    mine: MineSelect<false> | MineSelect<true>;
    mineFeatures: MineFeaturesSelect<false> | MineFeaturesSelect<true>;
    project: ProjectSelect<false> | ProjectSelect<true>;
    projectPhase: ProjectPhaseSelect<false> | ProjectPhaseSelect<true>;
    projectPartial: ProjectPartialSelect<false> | ProjectPartialSelect<true>;
    projectService: ProjectServiceSelect<false> | ProjectServiceSelect<true>;
    projectFlag: ProjectFlagSelect<false> | ProjectFlagSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'en') | ('de' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'de' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * WordPress news post ID — used by the News ETL for idempotent re-imports.
   */
  wpId?: number | null;
  name?: string | null;
  thumbnail?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  externalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award".
 */
export interface Award {
  id: number;
  name?: string | null;
  /**
   * Legacy jahr — used as the default sort key (newest first).
   */
  year?: number | null;
  thumbnail?: (number | null) | Media;
  issuer?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication".
 */
export interface Publication {
  id: number;
  /**
   * Legacy name/buch — publication titles are not localized in the legacy data.
   */
  name?: string | null;
  /**
   * Legacy untertitel/buchuntertitel.
   */
  subtitle?: string | null;
  category?: (number | null) | PublicationCategory;
  /**
   * Legacy jahr — used as the default sort key (newest first).
   */
  year?: number | null;
  thumbnail?: (number | null) | Media;
  /**
   * Legacy zeitschrift.
   */
  journal?: string | null;
  /**
   * Legacy verlag.
   */
  publisher?: string | null;
  /**
   * Legacy autor.
   */
  author?: string | null;
  /**
   * Legacy hrsg.
   */
  editor?: string | null;
  /**
   * Legacy seiten — kept as text since legacy values include ranges (e.g. "12-34").
   */
  pages?: string | null;
  /**
   * Legacy datei.
   */
  file?: (number | null) | Media;
  url?: string | null;
  /**
   * Legacy projekte — pipe-delimited list of project kuerzel codes.
   */
  projects?: (string | Project)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicationCategory".
 */
export interface PublicationCategory {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project".
 */
export interface Project {
  id: string;
  creationDate?: string | null;
  name: string;
  status?: ('planning' | 'construction' | 'done' | 'partially_done' | 'finished' | 'paused' | 'canceled') | null;
  /**
   * can be forecast aswell
   */
  yearCompletion?: number | null;
  /**
   * in ha
   */
  surfaceArea?: number | null;
  /**
   * hex code only
   */
  color?: string | null;
  active_in?: {
    intranet?: boolean | null;
    werkx?: boolean | null;
    web?: boolean | null;
  };
  adress?: {
    /**
     * @minItems 2
     * @maxItems 2
     */
    coords?: [number, number] | null;
    details?: {
      country?: string | null;
      city?: string | null;
      zip?: string | null;
      street?: string | null;
      more?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee".
 */
export interface Employee {
  id: number;
  firstName: string;
  lastName: string;
  fullName?: string | null;
  birthday?: string | null;
  office?: (number | null) | OfficeLocation;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  higherEducation?: {
    type?: ('bachelor' | 'master' | 'diplom' | 'doctor' | 'professor' | 'vocationalTraining' | 'other') | null;
    subType?: ('art' | 'sci' | 'eng' | 'ing') | null;
    name?: string | null;
    location?: string | null;
  };
  email?: string | null;
  /**
   * Please enter in international format starting with your country code.
   */
  phone?: string | null;
  /**
   * Please enter in international format starting with your country code.
   */
  mobilePhone?: string | null;
  werkx?: {
    /**
     * aka Kuerzel
     */
    slug?: string | null;
    /**
     * hex code only
     */
    color?: string | null;
    entry?: string | null;
    exit?: string | null;
    firstWorkYear?: number | null;
    startTrackingDate?: string | null;
    formerEmployee?: boolean | null;
    sollHistory?:
      | {
          targetHours: number;
          /**
           * Overtime/under-hours at the start of this period.
           */
          startingBalance?: number | null;
          start?: string | null;
          end?: string | null;
          distribution?: {
            mo?: number | null;
            di?: number | null;
            mi?: number | null;
            do?: number | null;
            fr?: number | null;
            sa?: number | null;
            so?: number | null;
          };
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    vacationClaims?:
      | {
          /**
           * Leave blank for a claim that applies indefinitely (a fallback, not tied to one year).
           */
          year?: number | null;
          days: number;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officeLocation".
 */
export interface OfficeLocation {
  id: number;
  name?: string | null;
  leader?: (number | null) | Employee;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  adress?: {
    /**
     * @minItems 2
     * @maxItems 2
     */
    coords?: [number, number] | null;
    details?: {
      country?: string | null;
      city?: string | null;
      zip?: string | null;
      street?: string | null;
      more?: string | null;
    };
  };
  contact?: {
    tel?: string | null;
    fax?: string | null;
    email?: string | null;
    emailIntern?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mine".
 */
export interface Mine {
  id: number;
  title: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  siteType?: ('open_cast' | 'external_dump' | 'underground' | 'quarry' | 'mountaintop_removal')[] | null;
  status?: ('in_use' | 'in_revitalization' | 'revitalized') | null;
  closureYear?: number | null;
  extractedMaterials?:
    | ('coal' | 'iron' | 'bauxite' | 'copper' | 'gold' | 'lithium' | 'nickel' | 'phosphorite' | 'silver' | 'zinc')[]
    | null;
  surface?: {
    total?: number | null;
    lake?: number | null;
    forest?: number | null;
    agriculture?: number | null;
    settlement?: number | null;
  };
  /**
   * What is this site used for now?
   */
  features?: (number | MineFeature)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mineFeatures".
 */
export interface MineFeature {
  id: number;
  name: string;
  iconName?: string | null;
  color?: ('blue' | 'green' | 'grey') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectPhase".
 */
export interface ProjectPhase {
  id: string;
  project: string | Project;
  phase?: string | null;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectPartial".
 */
export interface ProjectPartial {
  id: number;
  name: string;
  project: string | Project;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectService".
 */
export interface ProjectService {
  id: number;
  name: string;
  project: string | Project;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectFlag".
 */
export interface ProjectFlag {
  id: string;
  name: string;
  /**
   * in hours
   */
  timeBudget?: number | null;
  /**
   * hex code only
   */
  color?: string | null;
  project: string | Project;
  phase?: string | null;
  linkedPartial?: (number | null) | ProjectPartial;
  linkedService?: (number | null) | ProjectService;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'award';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'publication';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'publicationCategory';
        value: number | PublicationCategory;
      } | null)
    | ({
        relationTo: 'employee';
        value: number | Employee;
      } | null)
    | ({
        relationTo: 'officeLocation';
        value: number | OfficeLocation;
      } | null)
    | ({
        relationTo: 'mine';
        value: number | Mine;
      } | null)
    | ({
        relationTo: 'mineFeatures';
        value: number | MineFeature;
      } | null)
    | ({
        relationTo: 'project';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'projectPhase';
        value: string | ProjectPhase;
      } | null)
    | ({
        relationTo: 'projectPartial';
        value: number | ProjectPartial;
      } | null)
    | ({
        relationTo: 'projectService';
        value: number | ProjectService;
      } | null)
    | ({
        relationTo: 'projectFlag';
        value: string | ProjectFlag;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  wpId?: T;
  name?: T;
  thumbnail?: T;
  content?: T;
  externalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award_select".
 */
export interface AwardSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  thumbnail?: T;
  issuer?: T;
  content?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publication_select".
 */
export interface PublicationSelect<T extends boolean = true> {
  name?: T;
  subtitle?: T;
  category?: T;
  year?: T;
  thumbnail?: T;
  journal?: T;
  publisher?: T;
  author?: T;
  editor?: T;
  pages?: T;
  file?: T;
  url?: T;
  projects?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicationCategory_select".
 */
export interface PublicationCategorySelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee_select".
 */
export interface EmployeeSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  fullName?: T;
  birthday?: T;
  office?: T;
  content?: T;
  higherEducation?:
    | T
    | {
        type?: T;
        subType?: T;
        name?: T;
        location?: T;
      };
  email?: T;
  phone?: T;
  mobilePhone?: T;
  werkx?:
    | T
    | {
        slug?: T;
        color?: T;
        entry?: T;
        exit?: T;
        firstWorkYear?: T;
        startTrackingDate?: T;
        formerEmployee?: T;
        sollHistory?:
          | T
          | {
              targetHours?: T;
              startingBalance?: T;
              start?: T;
              end?: T;
              distribution?:
                | T
                | {
                    mo?: T;
                    di?: T;
                    mi?: T;
                    do?: T;
                    fr?: T;
                    sa?: T;
                    so?: T;
                  };
              description?: T;
              id?: T;
            };
        vacationClaims?:
          | T
          | {
              year?: T;
              days?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "officeLocation_select".
 */
export interface OfficeLocationSelect<T extends boolean = true> {
  name?: T;
  leader?: T;
  content?: T;
  adress?:
    | T
    | {
        coords?: T;
        details?:
          | T
          | {
              country?: T;
              city?: T;
              zip?: T;
              street?: T;
              more?: T;
            };
      };
  contact?:
    | T
    | {
        tel?: T;
        fax?: T;
        email?: T;
        emailIntern?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mine_select".
 */
export interface MineSelect<T extends boolean = true> {
  title?: T;
  location?: T;
  content?: T;
  siteType?: T;
  status?: T;
  closureYear?: T;
  extractedMaterials?: T;
  surface?:
    | T
    | {
        total?: T;
        lake?: T;
        forest?: T;
        agriculture?: T;
        settlement?: T;
      };
  features?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mineFeatures_select".
 */
export interface MineFeaturesSelect<T extends boolean = true> {
  name?: T;
  iconName?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project_select".
 */
export interface ProjectSelect<T extends boolean = true> {
  id?: T;
  creationDate?: T;
  name?: T;
  status?: T;
  yearCompletion?: T;
  surfaceArea?: T;
  color?: T;
  active_in?:
    | T
    | {
        intranet?: T;
        werkx?: T;
        web?: T;
      };
  adress?:
    | T
    | {
        coords?: T;
        details?:
          | T
          | {
              country?: T;
              city?: T;
              zip?: T;
              street?: T;
              more?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectPhase_select".
 */
export interface ProjectPhaseSelect<T extends boolean = true> {
  id?: T;
  project?: T;
  phase?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectPartial_select".
 */
export interface ProjectPartialSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  project?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectService_select".
 */
export interface ProjectServiceSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  project?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectFlag_select".
 */
export interface ProjectFlagSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  timeBudget?: T;
  color?: T;
  project?: T;
  phase?: T;
  linkedPartial?: T;
  linkedService?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}